"""add_is_active_to_resources

Revision ID: dfbd16c971e8
Revises: e9689ffff778
Create Date: 2026-10-01 11:06:56.210883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbd16c971e8'
down_revision = 'e9689ffff778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('student_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('student_groups', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
