"""initial_schema

Revision ID: e9689ffff778
Revises: 
Create Date: 2026-09-30 23:59:04.096941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9689ffff778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('building', sa.String(length=80), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('has_projector', sa.Boolean(), nullable=False),
    sa.Column('has_computers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("room_type IN ('classroom', 'laboratory')", name='ck_classroom_room_type_valid'),
    sa.CheckConstraint('capacity >= 1', name='ck_classroom_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'building', name='uq_classroom_name_building')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('max_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_hours_per_week', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_hours_per_day > 0', name='ck_faculty_max_hours_day_positive'),
    sa.CheckConstraint('max_hours_per_week > 0', name='ck_faculty_max_hours_week_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('semester >= 1', name='ck_group_semester_positive'),
    sa.CheckConstraint('student_count >= 1', name='ck_group_student_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('weekly_sessions', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('required_room_type', sa.String(length=20), nullable=False),
    sa.Column('requires_consecutive_slots', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("required_room_type IN ('classroom', 'laboratory')", name='ck_subject_room_type_valid'),
    sa.CheckConstraint("subject_type IN ('theory', 'practical', 'tutorial')", name='ck_subject_type_valid'),
    sa.CheckConstraint('duration_minutes >= 1', name='ck_subject_duration_positive'),
    sa.CheckConstraint('semester >= 1', name='ck_subject_semester_positive'),
    sa.CheckConstraint('weekly_sessions >= 1', name='ck_subject_weekly_sessions_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')", name='ck_time_slot_day_valid'),
    sa.CheckConstraint('end_time > start_time', name='ck_time_slot_end_after_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("generation_status IN ('pending', 'completed', 'failed')", name='ck_timetable_generation_status_valid'),
    sa.CheckConstraint("status IN ('draft', 'published')", name='ck_timetable_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty_subjects',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('faculty_id', 'subject_id')
    )
    op.create_table('group_subjects',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'subject_id')
    )
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_group_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_entries')
    op.drop_table('group_subjects')
    op.drop_table('faculty_subjects')
    op.drop_table('timetables')
    op.drop_table('time_slots')
    op.drop_table('subjects')
    op.drop_table('student_groups')
    op.drop_table('faculty')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
